name: Build Wheels

on:
  workflow_dispatch:
    inputs:
      requested_release_tag:
        description: 'The tag to use for this release (e.g., `v2.3.0`)'
        required: true

jobs:

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.3
        env:
          CIBW_SKIP: "pp*-macosx* *-win32 *-manylinux_i686"
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
